version: '2'
services:
  web:
    build: .
    command: npm start
    ports:
     - "8088:8088"
    depends_on:
     - mongo_express
     - mongodb
  mongo_express:
    image: "lga-registry01.pulse.prod:5000/mongodb_express_app:latest"
    environment:
     - MONGODB_HOST=mongodb
    ports:
     - "3000:3000"
    depends_on:
     - mongodb
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
    volumes:
     - /tmp/mongodb:/data/db

