version: '2'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - mongo_express
     - mongodb
  mongo_express:
    image: "mongodb_express_app:latest"
    environment:
     - MONGODB_HOST=mongodb
    ports:
     - "3000:3000"
    depends_on:
     - mongodb
  mongodb:
    image: "dockerfile/mongodb"
    ports:
     - "27017:27017"
    volumes:
     - /tmp/mongodb:/data/db

